listen:
  host: "127.0.0.1"
  https_port: 3130
  http_port: 3131

rules:
  - pattern: ".*\\.google\\.com"
    proxy: "DIRECT"
  - pattern: ".*\\.yandex\\.ru"
    proxy: "DIRECT"
  - pattern: ".*"
    proxy: "proxy.example.com:8080"